version: "3.8"

services:
  server:
    build: ./server
    image: minhancr123/megamart:server
    container_name: megamart_server
    env_file:
      - ./server/.env
    expose:
      - "3001"
    restart: always
    networks:
      - megamart-network

  nginx:
    image: minhancr123/megamart:nginx
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    container_name: megamart_nginx
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - megamart-network

networks:
  megamart-network:
    driver: bridge
